<?php

/**
 * Base class that represents a row from the 'comprobante' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Sep 21 18:14:56 2009
 *
 * @package    lib.model.om
 */
abstract class BaseComprobante extends BaseObject  implements Persistent {


  const PEER = 'ComprobantePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ComprobantePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the tipo_comprobante_id field.
	 * @var        int
	 */
	protected $tipo_comprobante_id;

	/**
	 * The value for the nro_comprobante field.
	 * @var        string
	 */
	protected $nro_comprobante;

	/**
	 * The value for the punto_venta field.
	 * @var        string
	 */
	protected $punto_venta;

	/**
	 * The value for the fecha_comprobante field.
	 * @var        string
	 */
	protected $fecha_comprobante;

	/**
	 * The value for the cliente_id field.
	 * @var        int
	 */
	protected $cliente_id;

	/**
	 * The value for the cbt_desde field.
	 * @var        int
	 */
	protected $cbt_desde;

	/**
	 * The value for the cbt_hasta field.
	 * @var        int
	 */
	protected $cbt_hasta;

	/**
	 * The value for the imp_total field.
	 * @var        double
	 */
	protected $imp_total;

	/**
	 * The value for the imp_total_conceptos field.
	 * @var        double
	 */
	protected $imp_total_conceptos;

	/**
	 * The value for the imp_neto field.
	 * @var        double
	 */
	protected $imp_neto;

	/**
	 * The value for the imp_liquidado field.
	 * @var        double
	 */
	protected $imp_liquidado;

	/**
	 * The value for the imp_liquidado_rni field.
	 * @var        double
	 */
	protected $imp_liquidado_rni;

	/**
	 * The value for the imp_operaciones_ex field.
	 * @var        double
	 */
	protected $imp_operaciones_ex;

	/**
	 * The value for the fecha_servicio_desde field.
	 * @var        string
	 */
	protected $fecha_servicio_desde;

	/**
	 * The value for the fecha_servicio_hasta field.
	 * @var        string
	 */
	protected $fecha_servicio_hasta;

	/**
	 * The value for the fecha_vencimiento_pago field.
	 * @var        string
	 */
	protected $fecha_vencimiento_pago;

	/**
	 * @var        TipoComprobante
	 */
	protected $aTipoComprobante;

	/**
	 * @var        Cliente
	 */
	protected $aCliente;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseComprobante object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [tipo_comprobante_id] column value.
	 * 
	 * @return     int
	 */
	public function getTipoComprobanteId()
	{
		return $this->tipo_comprobante_id;
	}

	/**
	 * Get the [nro_comprobante] column value.
	 * 
	 * @return     string
	 */
	public function getNroComprobante()
	{
		return $this->nro_comprobante;
	}

	/**
	 * Get the [punto_venta] column value.
	 * 
	 * @return     string
	 */
	public function getPuntoVenta()
	{
		return $this->punto_venta;
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_comprobante] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaComprobante($format = 'Y-m-d H:i:s')
	{
		if ($this->fecha_comprobante === null) {
			return null;
		}


		if ($this->fecha_comprobante === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fecha_comprobante);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_comprobante, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [cliente_id] column value.
	 * 
	 * @return     int
	 */
	public function getClienteId()
	{
		return $this->cliente_id;
	}

	/**
	 * Get the [cbt_desde] column value.
	 * 
	 * @return     int
	 */
	public function getCbtDesde()
	{
		return $this->cbt_desde;
	}

	/**
	 * Get the [cbt_hasta] column value.
	 * 
	 * @return     int
	 */
	public function getCbtHasta()
	{
		return $this->cbt_hasta;
	}

	/**
	 * Get the [imp_total] column value.
	 * 
	 * @return     double
	 */
	public function getImpTotal()
	{
		return $this->imp_total;
	}

	/**
	 * Get the [imp_total_conceptos] column value.
	 * 
	 * @return     double
	 */
	public function getImpTotalConceptos()
	{
		return $this->imp_total_conceptos;
	}

	/**
	 * Get the [imp_neto] column value.
	 * 
	 * @return     double
	 */
	public function getImpNeto()
	{
		return $this->imp_neto;
	}

	/**
	 * Get the [imp_liquidado] column value.
	 * 
	 * @return     double
	 */
	public function getImpLiquidado()
	{
		return $this->imp_liquidado;
	}

	/**
	 * Get the [imp_liquidado_rni] column value.
	 * 
	 * @return     double
	 */
	public function getImpLiquidadoRni()
	{
		return $this->imp_liquidado_rni;
	}

	/**
	 * Get the [imp_operaciones_ex] column value.
	 * 
	 * @return     double
	 */
	public function getImpOperacionesEx()
	{
		return $this->imp_operaciones_ex;
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_servicio_desde] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaServicioDesde($format = 'Y-m-d H:i:s')
	{
		if ($this->fecha_servicio_desde === null) {
			return null;
		}


		if ($this->fecha_servicio_desde === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fecha_servicio_desde);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_servicio_desde, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_servicio_hasta] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaServicioHasta($format = 'Y-m-d H:i:s')
	{
		if ($this->fecha_servicio_hasta === null) {
			return null;
		}


		if ($this->fecha_servicio_hasta === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fecha_servicio_hasta);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_servicio_hasta, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_vencimiento_pago] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaVencimientoPago($format = 'Y-m-d H:i:s')
	{
		if ($this->fecha_vencimiento_pago === null) {
			return null;
		}


		if ($this->fecha_vencimiento_pago === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fecha_vencimiento_pago);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_vencimiento_pago, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Comprobante The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ComprobantePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [tipo_comprobante_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Comprobante The current object (for fluent API support)
	 */
	public function setTipoComprobanteId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->tipo_comprobante_id !== $v) {
			$this->tipo_comprobante_id = $v;
			$this->modifiedColumns[] = ComprobantePeer::TIPO_COMPROBANTE_ID;
		}

		if ($this->aTipoComprobante !== null && $this->aTipoComprobante->getId() !== $v) {
			$this->aTipoComprobante = null;
		}

		return $this;
	} // setTipoComprobanteId()

	/**
	 * Set the value of [nro_comprobante] column.
	 * 
	 * @param      string $v new value
	 * @return     Comprobante The current object (for fluent API support)
	 */
	public function setNroComprobante($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nro_comprobante !== $v) {
			$this->nro_comprobante = $v;
			$this->modifiedColumns[] = ComprobantePeer::NRO_COMPROBANTE;
		}

		return $this;
	} // setNroComprobante()

	/**
	 * Set the value of [punto_venta] column.
	 * 
	 * @param      string $v new value
	 * @return     Comprobante The current object (for fluent API support)
	 */
	public function setPuntoVenta($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->punto_venta !== $v) {
			$this->punto_venta = $v;
			$this->modifiedColumns[] = ComprobantePeer::PUNTO_VENTA;
		}

		return $this;
	} // setPuntoVenta()

	/**
	 * Sets the value of [fecha_comprobante] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Comprobante The current object (for fluent API support)
	 */
	public function setFechaComprobante($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha_comprobante !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha_comprobante !== null && $tmpDt = new DateTime($this->fecha_comprobante)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fecha_comprobante = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = ComprobantePeer::FECHA_COMPROBANTE;
			}
		} // if either are not null

		return $this;
	} // setFechaComprobante()

	/**
	 * Set the value of [cliente_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Comprobante The current object (for fluent API support)
	 */
	public function setClienteId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->cliente_id !== $v) {
			$this->cliente_id = $v;
			$this->modifiedColumns[] = ComprobantePeer::CLIENTE_ID;
		}

		if ($this->aCliente !== null && $this->aCliente->getId() !== $v) {
			$this->aCliente = null;
		}

		return $this;
	} // setClienteId()

	/**
	 * Set the value of [cbt_desde] column.
	 * 
	 * @param      int $v new value
	 * @return     Comprobante The current object (for fluent API support)
	 */
	public function setCbtDesde($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->cbt_desde !== $v) {
			$this->cbt_desde = $v;
			$this->modifiedColumns[] = ComprobantePeer::CBT_DESDE;
		}

		return $this;
	} // setCbtDesde()

	/**
	 * Set the value of [cbt_hasta] column.
	 * 
	 * @param      int $v new value
	 * @return     Comprobante The current object (for fluent API support)
	 */
	public function setCbtHasta($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->cbt_hasta !== $v) {
			$this->cbt_hasta = $v;
			$this->modifiedColumns[] = ComprobantePeer::CBT_HASTA;
		}

		return $this;
	} // setCbtHasta()

	/**
	 * Set the value of [imp_total] column.
	 * 
	 * @param      double $v new value
	 * @return     Comprobante The current object (for fluent API support)
	 */
	public function setImpTotal($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->imp_total !== $v) {
			$this->imp_total = $v;
			$this->modifiedColumns[] = ComprobantePeer::IMP_TOTAL;
		}

		return $this;
	} // setImpTotal()

	/**
	 * Set the value of [imp_total_conceptos] column.
	 * 
	 * @param      double $v new value
	 * @return     Comprobante The current object (for fluent API support)
	 */
	public function setImpTotalConceptos($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->imp_total_conceptos !== $v) {
			$this->imp_total_conceptos = $v;
			$this->modifiedColumns[] = ComprobantePeer::IMP_TOTAL_CONCEPTOS;
		}

		return $this;
	} // setImpTotalConceptos()

	/**
	 * Set the value of [imp_neto] column.
	 * 
	 * @param      double $v new value
	 * @return     Comprobante The current object (for fluent API support)
	 */
	public function setImpNeto($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->imp_neto !== $v) {
			$this->imp_neto = $v;
			$this->modifiedColumns[] = ComprobantePeer::IMP_NETO;
		}

		return $this;
	} // setImpNeto()

	/**
	 * Set the value of [imp_liquidado] column.
	 * 
	 * @param      double $v new value
	 * @return     Comprobante The current object (for fluent API support)
	 */
	public function setImpLiquidado($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->imp_liquidado !== $v) {
			$this->imp_liquidado = $v;
			$this->modifiedColumns[] = ComprobantePeer::IMP_LIQUIDADO;
		}

		return $this;
	} // setImpLiquidado()

	/**
	 * Set the value of [imp_liquidado_rni] column.
	 * 
	 * @param      double $v new value
	 * @return     Comprobante The current object (for fluent API support)
	 */
	public function setImpLiquidadoRni($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->imp_liquidado_rni !== $v) {
			$this->imp_liquidado_rni = $v;
			$this->modifiedColumns[] = ComprobantePeer::IMP_LIQUIDADO_RNI;
		}

		return $this;
	} // setImpLiquidadoRni()

	/**
	 * Set the value of [imp_operaciones_ex] column.
	 * 
	 * @param      double $v new value
	 * @return     Comprobante The current object (for fluent API support)
	 */
	public function setImpOperacionesEx($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->imp_operaciones_ex !== $v) {
			$this->imp_operaciones_ex = $v;
			$this->modifiedColumns[] = ComprobantePeer::IMP_OPERACIONES_EX;
		}

		return $this;
	} // setImpOperacionesEx()

	/**
	 * Sets the value of [fecha_servicio_desde] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Comprobante The current object (for fluent API support)
	 */
	public function setFechaServicioDesde($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha_servicio_desde !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha_servicio_desde !== null && $tmpDt = new DateTime($this->fecha_servicio_desde)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fecha_servicio_desde = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = ComprobantePeer::FECHA_SERVICIO_DESDE;
			}
		} // if either are not null

		return $this;
	} // setFechaServicioDesde()

	/**
	 * Sets the value of [fecha_servicio_hasta] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Comprobante The current object (for fluent API support)
	 */
	public function setFechaServicioHasta($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha_servicio_hasta !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha_servicio_hasta !== null && $tmpDt = new DateTime($this->fecha_servicio_hasta)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fecha_servicio_hasta = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = ComprobantePeer::FECHA_SERVICIO_HASTA;
			}
		} // if either are not null

		return $this;
	} // setFechaServicioHasta()

	/**
	 * Sets the value of [fecha_vencimiento_pago] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Comprobante The current object (for fluent API support)
	 */
	public function setFechaVencimientoPago($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha_vencimiento_pago !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha_vencimiento_pago !== null && $tmpDt = new DateTime($this->fecha_vencimiento_pago)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fecha_vencimiento_pago = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = ComprobantePeer::FECHA_VENCIMIENTO_PAGO;
			}
		} // if either are not null

		return $this;
	} // setFechaVencimientoPago()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->tipo_comprobante_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->nro_comprobante = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->punto_venta = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->fecha_comprobante = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->cliente_id = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->cbt_desde = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->cbt_hasta = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->imp_total = ($row[$startcol + 8] !== null) ? (double) $row[$startcol + 8] : null;
			$this->imp_total_conceptos = ($row[$startcol + 9] !== null) ? (double) $row[$startcol + 9] : null;
			$this->imp_neto = ($row[$startcol + 10] !== null) ? (double) $row[$startcol + 10] : null;
			$this->imp_liquidado = ($row[$startcol + 11] !== null) ? (double) $row[$startcol + 11] : null;
			$this->imp_liquidado_rni = ($row[$startcol + 12] !== null) ? (double) $row[$startcol + 12] : null;
			$this->imp_operaciones_ex = ($row[$startcol + 13] !== null) ? (double) $row[$startcol + 13] : null;
			$this->fecha_servicio_desde = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->fecha_servicio_hasta = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->fecha_vencimiento_pago = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 17; // 17 = ComprobantePeer::NUM_COLUMNS - ComprobantePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Comprobante object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aTipoComprobante !== null && $this->tipo_comprobante_id !== $this->aTipoComprobante->getId()) {
			$this->aTipoComprobante = null;
		}
		if ($this->aCliente !== null && $this->cliente_id !== $this->aCliente->getId()) {
			$this->aCliente = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ComprobantePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ComprobantePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aTipoComprobante = null;
			$this->aCliente = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseComprobante:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ComprobantePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			ComprobantePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseComprobante:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseComprobante:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ComprobantePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseComprobante:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			ComprobantePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTipoComprobante !== null) {
				if ($this->aTipoComprobante->isModified() || $this->aTipoComprobante->isNew()) {
					$affectedRows += $this->aTipoComprobante->save($con);
				}
				$this->setTipoComprobante($this->aTipoComprobante);
			}

			if ($this->aCliente !== null) {
				if ($this->aCliente->isModified() || $this->aCliente->isNew()) {
					$affectedRows += $this->aCliente->save($con);
				}
				$this->setCliente($this->aCliente);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ComprobantePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ComprobantePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ComprobantePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aTipoComprobante !== null) {
				if (!$this->aTipoComprobante->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aTipoComprobante->getValidationFailures());
				}
			}

			if ($this->aCliente !== null) {
				if (!$this->aCliente->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCliente->getValidationFailures());
				}
			}


			if (($retval = ComprobantePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ComprobantePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getTipoComprobanteId();
				break;
			case 2:
				return $this->getNroComprobante();
				break;
			case 3:
				return $this->getPuntoVenta();
				break;
			case 4:
				return $this->getFechaComprobante();
				break;
			case 5:
				return $this->getClienteId();
				break;
			case 6:
				return $this->getCbtDesde();
				break;
			case 7:
				return $this->getCbtHasta();
				break;
			case 8:
				return $this->getImpTotal();
				break;
			case 9:
				return $this->getImpTotalConceptos();
				break;
			case 10:
				return $this->getImpNeto();
				break;
			case 11:
				return $this->getImpLiquidado();
				break;
			case 12:
				return $this->getImpLiquidadoRni();
				break;
			case 13:
				return $this->getImpOperacionesEx();
				break;
			case 14:
				return $this->getFechaServicioDesde();
				break;
			case 15:
				return $this->getFechaServicioHasta();
				break;
			case 16:
				return $this->getFechaVencimientoPago();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ComprobantePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getTipoComprobanteId(),
			$keys[2] => $this->getNroComprobante(),
			$keys[3] => $this->getPuntoVenta(),
			$keys[4] => $this->getFechaComprobante(),
			$keys[5] => $this->getClienteId(),
			$keys[6] => $this->getCbtDesde(),
			$keys[7] => $this->getCbtHasta(),
			$keys[8] => $this->getImpTotal(),
			$keys[9] => $this->getImpTotalConceptos(),
			$keys[10] => $this->getImpNeto(),
			$keys[11] => $this->getImpLiquidado(),
			$keys[12] => $this->getImpLiquidadoRni(),
			$keys[13] => $this->getImpOperacionesEx(),
			$keys[14] => $this->getFechaServicioDesde(),
			$keys[15] => $this->getFechaServicioHasta(),
			$keys[16] => $this->getFechaVencimientoPago(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ComprobantePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setTipoComprobanteId($value);
				break;
			case 2:
				$this->setNroComprobante($value);
				break;
			case 3:
				$this->setPuntoVenta($value);
				break;
			case 4:
				$this->setFechaComprobante($value);
				break;
			case 5:
				$this->setClienteId($value);
				break;
			case 6:
				$this->setCbtDesde($value);
				break;
			case 7:
				$this->setCbtHasta($value);
				break;
			case 8:
				$this->setImpTotal($value);
				break;
			case 9:
				$this->setImpTotalConceptos($value);
				break;
			case 10:
				$this->setImpNeto($value);
				break;
			case 11:
				$this->setImpLiquidado($value);
				break;
			case 12:
				$this->setImpLiquidadoRni($value);
				break;
			case 13:
				$this->setImpOperacionesEx($value);
				break;
			case 14:
				$this->setFechaServicioDesde($value);
				break;
			case 15:
				$this->setFechaServicioHasta($value);
				break;
			case 16:
				$this->setFechaVencimientoPago($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ComprobantePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setTipoComprobanteId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setNroComprobante($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setPuntoVenta($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setFechaComprobante($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setClienteId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCbtDesde($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCbtHasta($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setImpTotal($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setImpTotalConceptos($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setImpNeto($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setImpLiquidado($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setImpLiquidadoRni($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setImpOperacionesEx($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setFechaServicioDesde($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setFechaServicioHasta($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setFechaVencimientoPago($arr[$keys[16]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ComprobantePeer::DATABASE_NAME);

		if ($this->isColumnModified(ComprobantePeer::ID)) $criteria->add(ComprobantePeer::ID, $this->id);
		if ($this->isColumnModified(ComprobantePeer::TIPO_COMPROBANTE_ID)) $criteria->add(ComprobantePeer::TIPO_COMPROBANTE_ID, $this->tipo_comprobante_id);
		if ($this->isColumnModified(ComprobantePeer::NRO_COMPROBANTE)) $criteria->add(ComprobantePeer::NRO_COMPROBANTE, $this->nro_comprobante);
		if ($this->isColumnModified(ComprobantePeer::PUNTO_VENTA)) $criteria->add(ComprobantePeer::PUNTO_VENTA, $this->punto_venta);
		if ($this->isColumnModified(ComprobantePeer::FECHA_COMPROBANTE)) $criteria->add(ComprobantePeer::FECHA_COMPROBANTE, $this->fecha_comprobante);
		if ($this->isColumnModified(ComprobantePeer::CLIENTE_ID)) $criteria->add(ComprobantePeer::CLIENTE_ID, $this->cliente_id);
		if ($this->isColumnModified(ComprobantePeer::CBT_DESDE)) $criteria->add(ComprobantePeer::CBT_DESDE, $this->cbt_desde);
		if ($this->isColumnModified(ComprobantePeer::CBT_HASTA)) $criteria->add(ComprobantePeer::CBT_HASTA, $this->cbt_hasta);
		if ($this->isColumnModified(ComprobantePeer::IMP_TOTAL)) $criteria->add(ComprobantePeer::IMP_TOTAL, $this->imp_total);
		if ($this->isColumnModified(ComprobantePeer::IMP_TOTAL_CONCEPTOS)) $criteria->add(ComprobantePeer::IMP_TOTAL_CONCEPTOS, $this->imp_total_conceptos);
		if ($this->isColumnModified(ComprobantePeer::IMP_NETO)) $criteria->add(ComprobantePeer::IMP_NETO, $this->imp_neto);
		if ($this->isColumnModified(ComprobantePeer::IMP_LIQUIDADO)) $criteria->add(ComprobantePeer::IMP_LIQUIDADO, $this->imp_liquidado);
		if ($this->isColumnModified(ComprobantePeer::IMP_LIQUIDADO_RNI)) $criteria->add(ComprobantePeer::IMP_LIQUIDADO_RNI, $this->imp_liquidado_rni);
		if ($this->isColumnModified(ComprobantePeer::IMP_OPERACIONES_EX)) $criteria->add(ComprobantePeer::IMP_OPERACIONES_EX, $this->imp_operaciones_ex);
		if ($this->isColumnModified(ComprobantePeer::FECHA_SERVICIO_DESDE)) $criteria->add(ComprobantePeer::FECHA_SERVICIO_DESDE, $this->fecha_servicio_desde);
		if ($this->isColumnModified(ComprobantePeer::FECHA_SERVICIO_HASTA)) $criteria->add(ComprobantePeer::FECHA_SERVICIO_HASTA, $this->fecha_servicio_hasta);
		if ($this->isColumnModified(ComprobantePeer::FECHA_VENCIMIENTO_PAGO)) $criteria->add(ComprobantePeer::FECHA_VENCIMIENTO_PAGO, $this->fecha_vencimiento_pago);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ComprobantePeer::DATABASE_NAME);

		$criteria->add(ComprobantePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Comprobante (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setTipoComprobanteId($this->tipo_comprobante_id);

		$copyObj->setNroComprobante($this->nro_comprobante);

		$copyObj->setPuntoVenta($this->punto_venta);

		$copyObj->setFechaComprobante($this->fecha_comprobante);

		$copyObj->setClienteId($this->cliente_id);

		$copyObj->setCbtDesde($this->cbt_desde);

		$copyObj->setCbtHasta($this->cbt_hasta);

		$copyObj->setImpTotal($this->imp_total);

		$copyObj->setImpTotalConceptos($this->imp_total_conceptos);

		$copyObj->setImpNeto($this->imp_neto);

		$copyObj->setImpLiquidado($this->imp_liquidado);

		$copyObj->setImpLiquidadoRni($this->imp_liquidado_rni);

		$copyObj->setImpOperacionesEx($this->imp_operaciones_ex);

		$copyObj->setFechaServicioDesde($this->fecha_servicio_desde);

		$copyObj->setFechaServicioHasta($this->fecha_servicio_hasta);

		$copyObj->setFechaVencimientoPago($this->fecha_vencimiento_pago);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Comprobante Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ComprobantePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ComprobantePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a TipoComprobante object.
	 *
	 * @param      TipoComprobante $v
	 * @return     Comprobante The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTipoComprobante(TipoComprobante $v = null)
	{
		if ($v === null) {
			$this->setTipoComprobanteId(NULL);
		} else {
			$this->setTipoComprobanteId($v->getId());
		}

		$this->aTipoComprobante = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the TipoComprobante object, it will not be re-added.
		if ($v !== null) {
			$v->addComprobante($this);
		}

		return $this;
	}


	/**
	 * Get the associated TipoComprobante object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     TipoComprobante The associated TipoComprobante object.
	 * @throws     PropelException
	 */
	public function getTipoComprobante(PropelPDO $con = null)
	{
		if ($this->aTipoComprobante === null && ($this->tipo_comprobante_id !== null)) {
			$c = new Criteria(TipoComprobantePeer::DATABASE_NAME);
			$c->add(TipoComprobantePeer::ID, $this->tipo_comprobante_id);
			$this->aTipoComprobante = TipoComprobantePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aTipoComprobante->addComprobantes($this);
			 */
		}
		return $this->aTipoComprobante;
	}

	/**
	 * Declares an association between this object and a Cliente object.
	 *
	 * @param      Cliente $v
	 * @return     Comprobante The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCliente(Cliente $v = null)
	{
		if ($v === null) {
			$this->setClienteId(NULL);
		} else {
			$this->setClienteId($v->getId());
		}

		$this->aCliente = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Cliente object, it will not be re-added.
		if ($v !== null) {
			$v->addComprobante($this);
		}

		return $this;
	}


	/**
	 * Get the associated Cliente object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Cliente The associated Cliente object.
	 * @throws     PropelException
	 */
	public function getCliente(PropelPDO $con = null)
	{
		if ($this->aCliente === null && ($this->cliente_id !== null)) {
			$c = new Criteria(ClientePeer::DATABASE_NAME);
			$c->add(ClientePeer::ID, $this->cliente_id);
			$this->aCliente = ClientePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCliente->addComprobantes($this);
			 */
		}
		return $this->aCliente;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aTipoComprobante = null;
			$this->aCliente = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseComprobante:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseComprobante::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseComprobante
