<?php


/**
 * This class adds structure of 'comprobante' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Sep 21 18:14:56 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ComprobanteMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ComprobanteMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(ComprobantePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(ComprobantePeer::TABLE_NAME);
		$tMap->setPhpName('Comprobante');
		$tMap->setClassname('Comprobante');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('TIPO_COMPROBANTE_ID', 'TipoComprobanteId', 'INTEGER', 'tipo_comprobante', 'ID', false, null);

		$tMap->addColumn('NRO_COMPROBANTE', 'NroComprobante', 'VARCHAR', true, 255);

		$tMap->addColumn('PUNTO_VENTA', 'PuntoVenta', 'VARCHAR', true, 255);

		$tMap->addColumn('FECHA_COMPROBANTE', 'FechaComprobante', 'TIMESTAMP', true, null);

		$tMap->addForeignKey('CLIENTE_ID', 'ClienteId', 'INTEGER', 'cliente', 'ID', false, null);

		$tMap->addColumn('CBT_DESDE', 'CbtDesde', 'INTEGER', true, null);

		$tMap->addColumn('CBT_HASTA', 'CbtHasta', 'INTEGER', true, null);

		$tMap->addColumn('IMP_TOTAL', 'ImpTotal', 'REAL', true, null);

		$tMap->addColumn('IMP_TOTAL_CONCEPTOS', 'ImpTotalConceptos', 'REAL', true, null);

		$tMap->addColumn('IMP_NETO', 'ImpNeto', 'REAL', true, null);

		$tMap->addColumn('IMP_LIQUIDADO', 'ImpLiquidado', 'REAL', true, null);

		$tMap->addColumn('IMP_LIQUIDADO_RNI', 'ImpLiquidadoRni', 'REAL', true, null);

		$tMap->addColumn('IMP_OPERACIONES_EX', 'ImpOperacionesEx', 'REAL', true, null);

		$tMap->addColumn('FECHA_SERVICIO_DESDE', 'FechaServicioDesde', 'TIMESTAMP', false, null);

		$tMap->addColumn('FECHA_SERVICIO_HASTA', 'FechaServicioHasta', 'TIMESTAMP', false, null);

		$tMap->addColumn('FECHA_VENCIMIENTO_PAGO', 'FechaVencimientoPago', 'TIMESTAMP', false, null);

	} // doBuild()

} // ComprobanteMapBuilder
